spring:
  application:
    name: member-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
feign:
  client:
    config:
      default:
        retryer: feign.Retryer.Default
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://gpadmin:1234@localhost:8761/eureka} # Jenkins 환경변수 EUREKA_URL이 있으면 사용, 없으면 localhost
server:
  port: 9001

#?db 9000, 3306